trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: Observation

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g serverless
    npm i
  displayName: 'npm install'

#- script: |
  #  npm run test
  #displayName: 'npm test'

- script: |
    export AWS_ACCESS_KEY_ID=$(AWS_ACCT_ID)
    export AWS_SECRET_ACCESS_KEY=$(AWS_ACCT_SECRET)
    serverless config credentials --provider aws --key $$AWS_ACCT_ID --secret $$AWS_ACCT_SECRET
    sls package --package api.o9y
  displayName: 'serverless package'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'api.o9y'
    targetPath: 'api.o9y'