trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: Observation

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd observatory-api
    npm install -g serverless
  displayName: 'npm install'

#- script: |
  #  npm run test
  #displayName: 'npm test'

- script: |
    export AWS_ACCESS_KEY_ID=$(AWS_ACCT_ID)
    export AWS_SECRET_ACCESS_KEY=$(AWS_ACCT_SECRET)
    serverless config credentials --provider aws --key $$AWS_ACCT_ID --secret $$AWS_ACCT_SECRET
    sls deploy
  displayName: 'serverless deploy'