service: observatory-api

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-east-1

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.o9y.soma.farm
    basePath: ''
    stage: ${self:provider.stage}
    certificateName: 'soma.farm'
    createRoute53Record: false

functions:
  observationGetUploadUrl:
    handler: src/observation/observation-handler.getUploadURL

    events:
      - http:
          path: observation
          method: get
          request:
            template:
              application/json: >
                {
                  "fileType" : "$input.params('fileType')"
                }
          cors: true

  observationGetLatest:
    handler: src/observation/observation-handler.getLatest

    events:
      - http:
          path: observation/latest
          method: get
          cors: true