service: observatory-api

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::o9y.observations/*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::o9y.observations"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ ReactionsTable, Arn ]

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.o9y.soma.farm
    basePath: ''
    stage: ${self:provider.stage}
    certificateName: 'api.o9y.soma.farm'
    createRoute53Record: false

functions:
  observationGetUploadUrl:
    handler: src/observation/observation-handler.getUploadURL

    events:
      - http:
          path: observation
          method: get
          request:
            template:
              application/json: >
                {
                  "fileType" : "$input.params('fileType')"
                }
          cors: true

  observationGetLatest:
    handler: src/observation/observation-handler.getLatest

    events:
      - http:
          path: observation/latest
          method: get
          cors: true

  recordReaction:
    handler: src/reaction/reaction-handler.recordReaction

    events:
      - http:
          path: reaction
          method: post
          cors: true

resources:
  Resources:
    ReactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: reactions
        AttributeDefinitions:
          - AttributeName: reaction_type
            AttributeType: S
          - AttributeName: datetime
            AttributeType: N
        KeySchema:
          - AttributeName: reaction_type
            KeyType: HASH
          - AttributeName: datetime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5